name: "[Release] Publish Canary Version"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry Run Mode"
        type: boolean
        default: false
  push:
    branches: [main]

jobs:
  check-before-publishing:
    name: Checks before publishing
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.canary-release-version.outputs.version }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4   

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"  

      - name: Install Deps via Bun
        run: bun install    
      
      - name: Run checks before publishing
        run: bun test
      
      - name: Create NPM Canary release
        id: canary-release-version
        run: |
          VERSION=$(bun release:ci:canary)
          echo "Version from script: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  publish-to-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: check-before-publishing
    permissions:
      contents: read
      packages: write # for GitHub Packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      
      - name: Update version in package.json
        run: |
          bun .github/scripts/bump-version.ts --version=${{ needs.check-before-publishing.outputs.version }} --tag=next --suffix=${{ github.run_number }}

      - name: Install dependencies
        run: bun install

      - name: Authenticate with NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.ORG_MQIO_NPM_TOKEN }}" > ~/.npmrc

      - name: Build
        run: bun .github/scripts/build-and-bundle.ts

      - name: Publish to NPM (canary)
        run: |
          CMD="npm publish --tag next --access public"
          if [[ "${{ inputs.dryRun }}" == "true" ]]; then
            CMD="$CMD --dry-run"
          fi
          echo "Running: $CMD"
          eval "$CMD"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_MQIO_NPM_TOKEN }}

  publish-to-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    needs: check-before-publishing
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      
      - name: Update version in package.json & jsr.json 
        run: |
          bun .github/scripts/bump-version.ts --version=${{ needs.check-before-publishing.outputs.version }} --tag=next --suffix=${{ github.run_number }}
          bun .github/scripts/jsrSetup.ts

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun .github/scripts/build-and-bundle.ts

      - name: Publish to JSR (canary)
        run: |
          CMD="bunx jsr publish --allow-dirty"
          if [[ "${{ inputs.dryRun }}" == "true" ]]; then
            CMD="$CMD --dry-run"
          fi
          echo "Running: $CMD"
          eval "$CMD"