
name: "[Release] Release Stable Version"
on: 
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Bump Version & Create Release Notes
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2

    - name: Initialize Git user
      run: |
        git config --global user.email "bot@mainqueue.io"
        git config --global user.name "MainQueue.io Bot"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        registry-url: https://registry.npmjs.org/

    - name: Setup Bun.js
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".bun-version"

    - name: Install the dependancies
      run: bun install

    - name: Authenticate with NPM
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.ORG_MQIO_NPM_TOKEN }}" > ~/.npmrc
    
    - name: Build dist files with tsc
      run: bun .github/scripts/build-and-bundle.ts
    
    - name: Create Release
      run: |
        bun release:ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.ORG_MQIO_NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.ORG_MQIO_NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  publish-jsr:
    runs-on: ubuntu-latest
    name: Publish to JSR
    needs: release
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
        
      - name: Update version in jsr.json
        run: |
          bun .github/scripts/jsrSetup.ts

      - name: Install the dependancies
        run: bun install

      - name: Publish JSR
        run: |
          bunx jsr publish